# 1. Create an array that starts from 1, ends at 20, incremented by 3

In [1]:
import numpy as np

arr1 = np.arange(1, 21, 3)
print("Array 1:", arr1)

Array 1: [ 1  4  7 10 13 16 19]


# 2. Create a new array of shape 3 with random numbers between 0 and 1

In [2]:
arr2 = np.random.rand(3)
print("Array 2:", arr2)

Array 2: [0.66534861 0.1979538  0.51230882]


# 3. Create a 2D array and perform slicing operations

In [3]:
arr3 = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

arr3 = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
print("Original 2D Array:")
print(arr3)

# Slicing to get the first two rows
print("First two rows:")
print(arr3[:2])

# Slicing to get the last two rows
print("Last two rows:")
print(arr3[1:])

Original 2D Array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]
First two rows:
[[10 20 45]
 [30 12 16]]
Last two rows:
[[30 12 16]
 [42 17 56]]


# 4. Create two 2x2 arrays and demonstrate stacking and splitting


In [4]:
arr4 = np.array([[1, 2], [3, 4]])
arr5 = np.array([[5, 6], [7, 8]])

# Stack vertically
print("Stack vertically:")
print(np.vstack((arr4, arr5)))

# Stack horizontally
print("Stack horizontally:")
print(np.hstack((arr4, arr5)))

# Split arrays
print("Split horizontally:")
print(np.hsplit(arr4, 2))

Stack vertically:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Stack horizontally:
[[1 2 5 6]
 [3 4 7 8]]
Split horizontally:
[array([[1],
       [3]]), array([[2],
       [4]])]


# 5. Perform Matrix operations

In [5]:
# 5. Matrix operations
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Matrix multiplication
print("Matrix multiplication:")
try:
    print(np.dot(X, Y))
except ValueError:
    print("Matrix dimensions incompatible for multiplication.")




Matrix multiplication:
[[70 28]
 [70 30]
 [60 26]]


# 6. Vector operations and reshaping:

In [6]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Shape and dimensions
print("Shape of x:", x.shape)
print("Dimensions of x:", x.ndim)

# Reshape
x_reshaped = x.reshape((3, 1))
y_reshaped = y.reshape((3, 1))
print("Reshaped x:", x_reshaped)
print("Dimensions of reshaped x:", x_reshaped.ndim)
print("Reshaped y:", y_reshaped)
print("Dimensions of reshaped y:", y_reshaped.ndim)


Shape of x: (3,)
Dimensions of x: 1
Reshaped x: [[ 2]
 [-1]
 [-8]]
Dimensions of reshaped x: 2
Reshaped y: [[ 3]
 [ 1]
 [-2]]
Dimensions of reshaped y: 2


# 7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

In [7]:
# Broadcasting in subtraction
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 0, 1])
print("Broadcasting in subtraction:")
print(a - b)

# Broadcasting in multiplication
c = np.array([[1], [2], [3]])
d = np.array([0, 1, 2])
print("Broadcasting in multiplication:")
print(c * d)

Broadcasting in subtraction:
[[0 2 2]
 [3 5 5]
 [6 8 8]]
Broadcasting in multiplication:
[[0 1 2]
 [0 2 4]
 [0 3 6]]
